version: "3.9"

services:

  webapp-react.dev:
    container_name: webapp-react.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4201:4201
    environment:
      - CHOKIDAR_USEPOLLING=true